version: 2.1

executors:
  golang-executor:
    docker:
      - image: cimg/go:1.21
  node-executor:
    docker:
      - image: cimg/node:18.17.1
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint
    steps:
      - checkout
      - run:
          name: Run Hadolint
          command: hadolint Dockerfile

  test-app:
    executor: golang-executor
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t yourdockerhub/karsajobs:latest .
      - run:
          name: Push to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push yourdockerhub/karsajobs:latest

  build-app-karsajobs-ui:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t yourdockerhub/karsajobs-ui:latest .
      - run:
          name: Push to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push yourdockerhub/karsajobs-ui:latest

workflows:
  version: 2
  backend-workflow:
    when:
      condition:
        equal: [ "karsajobs", << pipeline.git.branch >> ]
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs:
          requires:
            - test-app

  frontend-workflow:
    when:
      condition:
        equal: [ "karsajobs-ui", << pipeline.git.branch >> ]
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui
