name: CI for karsajobs-ui (Frontend)

on:
  push:
    branches:
      - karsajobs-ui
  pull_request:
    branches:
      - karsajobs-ui

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install hadolint
        run: |
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint

      - name: Lint Dockerfile
        run: hadolint Dockerfile

  build-app-karsajobs-ui:
    runs-on: ubuntu-latest
    needs: lint-dockerfile
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/karsajobs-ui:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/karsajobs-ui:latest
